### ISSUE TITLE
4.19.y-imx8 Debian Buster/Bullseye: No Linux firewall works out of the box

### ISSUE THREAD

**Issue by skrueger8** [Artox/deb-pkg_kernel-cubox-i#1]
With the Debian Buster/Bullseye images (see https://images.solid-build.xyz/IMX8/Debian/), no Linux firewall solution works on the i.MX8 based boards right now:

```
root@sr-imx8:~# uname -a
Linux sr-imx8 4.19.72-imx8-sr #1 SMP PREEMPT Sat Nov 30 19:25:54 UTC 2019 aarch64 GNU/Linux

root@sr-imx8:~# dpkg -l linux-image\*
[...]
ii  linux-image-4.19.y-imx8-sr 4.19.72+3    arm64        LONGNAME kernel

root@sr-imx8:~# iptables -S
iptables/1.8.3 Failed to initialize nft: Protocol not supported

root@sr-imx8:~# nft list ruleset
mnl.c:42: Unable to initialize Netlink socket: Protocol not supported
```
https://wiki.nftables.org/wiki-nftables/index.php/Building_and_installing_nftables_from_sources has some hints which kernel options have to be enabled for nft support...

**Comment by Josua-SR** [comment]
Thanks for bringing this up!

It appears that the linux does not enable any of these options by default, so I got to figure out which ones are needed.
I'll be pushing a configuration update soon to try with.

**Comment by Josua-SR** [comment]
I have mass-enabled all of netfilter. An update package should have landed in the repos by tomorrow, but feel free to `dpkg-buildpackage` and try for yourself.

**Comment by skrueger8** [comment]
Works fine now, thanks! :)

```
root@sr-imx8:~# dpkg -l linux-image-4.19.y-imx8-sr
...
ii  linux-image-4.19.y-imx8-sr 4.19.72+4    arm64        LONGNAME kernel

root@sr-imx8:~# systemctl status nftables
● nftables.service - nftables
   Loaded: loaded (/lib/systemd/system/nftables.service; enabled; vendor preset: enabled)
   Active: active (exited) since Tue 2019-12-03 20:53:33 CET; 3s ago
...

root@sr-imx8:~# nft list ruleset
table ip filter {
        chain input {
                type filter hook input priority filter; policy drop;
                ct state established,related counter packets 7932 bytes 4131322 accept
...
```
