### ISSUE TITLE
Please enable ppp/pppoe kernel modules

### ISSUE THREAD

**Issue by skrueger8** [Artox/deb-pkg_kernel-cubox-i#3]
Hi,

I need one more favor. The Hummingboard Pulse is one of the few ARM SBCs with 2 Ethernet ports and I want to use it as a PPPoE router. Unfortunately the PPP/PPPoE kernel modules are not enabled. Could you please add them?

```
CONFIG_PPP_ASYNC=m
CONFIG_PPP_BSDCOMP=m
CONFIG_PPP_DEFLATE=m
CONFIG_PPP_FILTER=y
CONFIG_PPP_MULTILINK=y
CONFIG_PPP_SYNC_TTY=m
CONFIG_PPP=m
CONFIG_PPPOE=m
```

Thanks :)

**Comment by Josua-SR** [comment]
Thanks, applied. I will however wait with uploading to the repo and see if I come across other changes.
